name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Start Docker Compose
      run: docker-compose up -d

    - name: Test website
      run: docker exex -i phpmyadmin sh curl localhost:8080

    - name: Stop Docker Compose
      run: docker-compose down
