name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Start Docker Compose
      run: docker-compose up -d

    - name: Test website
      run: docker compose exec -T phpmyadmin curl localhost:80

    - name: Stop Docker Compose
      run: docker-compose down
